"""add file upload id

Revision ID: a72a04ac609e
Revises: 90ed05df20d7
Create Date: 2022-05-17 15:11:11.281799+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a72a04ac609e"
down_revision = "90ed05df20d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_meta_data", sa.Column("upload_id", sa.String(), nullable=True))
    op.add_column(
        "file_meta_data", sa.Column("expires_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_meta_data", "upload_id")
    op.drop_column("file_meta_data", "expires_at")
    # ### end Alembic commands ###
